services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - dnsapp_network
    command: npm run dev
    working_dir: /app

networks:
  dnsapp_network:
    name: dnsapp_network
    external: true